---

 - name: install the 'Development tools' package group
   yum:
     name: "@Development tools"
     state: present
    
 - name: Install required software
   yum:  pkg={{ item }} state=present   
   with_items:
     - openssl 
     - openssl-devel 
     - libffi 
     - libffi-devel 
     - python 
     - python-devel
     - python-cryptography 
     - pyOpenSSL.x86_64
   when: ansible_os_family == "RedHat"

 - name: Download Ansible-Tower
   get_url:
    url: http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz
    dest: /tmp
       
 - name: Extract Ansible-Tower
   unarchive:
     src: /tmp/ansible-tower-setup-latest.tar.gz
     dest: /tmp
     remote_src: yes
     list_files: yes
   register: archive_contents
   
 - name: Building the inventory
   template:
     src=inventory.j2
     dest=/tmp/{{ archive_contents.files[0] }}inventory   
   
 - name: Save it to variable!
   shell: echo "/tmp/{{ archive_contents.files[0] }}setup.sh" > /tmp/lastcommand.sh  
   
 - name: Change owner group mode of lastcommand
   file:
     path: /tmp/lastcommand.sh
     owner: root
     group: root
     mode: 0775   

 - name: If nothing execute after this!  Copy below on your shell and execute it!
   debug:
     msg: "/tmp/{{ archive_contents.files[0] }}setup.sh"  
